name: Release all packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Release all packages
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Release all packages
        uses: Backend-RA2-Tech/composite-workflows/lerna-template/release@main
        with:
          packages-directory: ./packages